# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-24 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportevial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportevial',
            name='latitud',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reportevial',
            name='longitud',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
